language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t pankajbi/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true pankajbi/docker-react npm run test
